### ISSUE TITLE
(Proposal) Make Switch even more FQL

### ISSUE THREAD

**Issue by gahabeen** [shiftx/faunadb-fql-lib#1]
I often check you lib when I need to build functions I havn't yet.
I just came uppon your Switch version and felt like it could even more FQL-centered.

For example, an old version of mine looks like this:

```ts
import { query as q, Expr } from 'faunadb';

export function Switch(value: Expr, cases: Expr, defaultValue: Expr = undefined) {
  const SWITCH_DEFAULT = '$$SWITCH_DEFAULT';
  return q.Let(
    {
      result: q.Reduce(
        q.Lambda(
          ['switch', 'caseAction'],
          q.If(q.Equals(value, q.Select(0, q.Var('caseAction'))), q.Select(1, q.Var('caseAction')), q.Var('switch')),
        ),
        SWITCH_DEFAULT,
        q.ToArray(cases),
      ),
    },
    q.If(q.Equals(q.Var('result'), SWITCH_DEFAULT), defaultValue, q.Var('result')),
  );
}
```

(I think I've got a SWITCH_DEFAULT const because reduce didn't like the idea of null when defaultValue is null)

Just a thought :)

**Comment by eigilsagafos** [comment]
Nice :) I like the approach. The reason I have done it the way I have (and therefore it's not as FQLy as I would like) is because I want to be able to provide expressions in the "cases" object that only evaluate if the case is met. I believe there are changes coming to FQL that will allow us to do this and also stay 100% FQL pure :)
